# -*- coding: utf-8 -*-
"""Stereo_depth_point_cloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Is6u16RBbar1eV93fkAAdzCvUYIPyj8c
"""

!pip install opencv-contrib-python matplotlib numpy

!wget -O left.png https://vision.middlebury.edu/stereo/data/scenes2021/data/artroom1/im0.png
!wget -O right.png https://vision.middlebury.edu/stereo/data/scenes2021/data/artroom1/im1.png

!ls /content/

import cv2
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import cv2.ximgproc as xip

# -------------------------
# Camera parameters
# -------------------------
fx = 1733.74
fy = 1733.74
cx = 792.27
cy = 541.89
baseline = 0.53662  # meters

# -------------------------
# 1. Load stereo images
# -------------------------
imgL = cv2.imread('/content/left.png', cv2.IMREAD_GRAYSCALE)
imgR = cv2.imread('/content/right.png', cv2.IMREAD_GRAYSCALE)
imgL = cv2.resize(imgL, (1920,1080))
imgR = cv2.resize(imgR, (1920,1080))

# -------------------------
# 2. Apply CLAHE to improve contrast
# -------------------------
clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
imgL_eq = clahe.apply(imgL)
imgR_eq = clahe.apply(imgR)

# -------------------------
# 3. Compute disparity with SGBM
# -------------------------
numDisparities = 192  # must be multiple of 16
blockSize = 5

stereo_left = cv2.StereoSGBM_create(
    minDisparity=0,
    numDisparities=numDisparities,
    blockSize=blockSize,
    P1=8*3*blockSize**2,
    P2=32*3*blockSize**2,
    mode=cv2.STEREO_SGBM_MODE_SGBM_3WAY
)

# Right matcher and WLS filter for higher quality
stereo_right = xip.createRightMatcher(stereo_left)
wls_filter = xip.createDisparityWLSFilter(matcher_left=stereo_left)
wls_filter.setLambda(4000)
wls_filter.setSigmaColor(1.5)

disp_left = stereo_left.compute(imgL_eq, imgR_eq)
disp_right = stereo_right.compute(imgR_eq, imgL_eq)
disp_filtered = wls_filter.filter(disp_left, imgL_eq, None, disp_right)

disp_filtered = np.float32(disp_filtered)/16.0
disp_filtered[disp_filtered < 1.0] = 1.0  # prevent division by zero

# Optional smoothing for cleaner disparity
disp_filtered = cv2.bilateralFilter(disp_filtered, d=5, sigmaColor=50, sigmaSpace=50)

# -------------------------
# 4. Compute depth map
# -------------------------
depth = (fx * baseline) / disp_filtered

# Mask valid depth values for visualization
mask_valid = (depth > 0) & (depth < 12)
vmin = np.percentile(depth[mask_valid], 5)
vmax = np.percentile(depth[mask_valid], 95)

plt.figure(figsize=(6,5))
plt.imshow(depth, cmap='viridis', vmin=vmin, vmax=vmax)
plt.colorbar(label='Depth (meters)')
plt.title("Depth Map")
plt.axis('off')
plt.show()

# -------------------------
# 5. Generate 3D point cloud
# -------------------------
height, width = depth.shape
u, v = np.meshgrid(np.arange(width), np.arange(height))

X = (u - cx) * depth / fx
Y = (v - cy) * depth / fy
Z = depth

points = np.stack((X.flatten(), Y.flatten(), Z.flatten()), axis=-1)
colors = cv2.cvtColor(cv2.resize(imgL, (width, height)), cv2.COLOR_GRAY2RGB)
colors = colors.reshape(-1,3) / 255.0

mask = (Z.flatten() > 7.0) & (Z.flatten() < 8.5)
points = points[mask]
colors = colors[mask]
points_sampled = points[::2]
colors_sampled = colors[::2]
# -------------------------
# 6. Visualize point cloud from selected view
# -------------------------
fig = plt.figure(figsize=(12,8))
ax = fig.add_subplot(111, projection='3d')

# Scatter 3D points
ax.scatter(points_sampled[:,0], points_sampled[:,1], points_sampled[:,2], c=colors_sampled, s=0.3)

ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')

# Set camera view: optimal angle for the scene
ax.view_init(elev=270, azim=90)
plt.title('3D Point Cloud')
plt.show()
